version: '2.1'
services:
 database:
   container_name: dhis2-database
   image: mdillon/postgis:9.5
   environment:
     POSTGRES_USER: dhis2
     POSTGRES_DB: dhis2
     POSTGRES_PASSWORD: dhis2
     POSTGRES_DB_TARGET: dhis-target
     PG_DATA: /var/lib/postgresql/data/pgdata:z
   ports:
    - "5435:5432"
   healthcheck:
     test: ["CMD-SHELL", "pg_isready -h database -p 5432 -d dhis2"]
     interval: 30s
     timeout: 30s
     retries: 150
 webapp:
   container_name: dhis2-webapp
   image: dhis2/dhis2-web:2.27-tomcat7-jre8-latest
   environment:
     JAVA_OPTS: "-Xmx1024m -Xms4000m"
     POSTGRES_DB: dhis2
   ports:
     - "8085:8080"
   depends_on:
     database:
       condition: service_healthy
   volumes:
     - "./fgs/dhis.conf:/opt/dhis2/config/dhis.conf"
   healthcheck:
     test: "curl -f http://webapp:8080"
     interval: 30s
     retries: 150
