version: '2.1'
services:
 webapp:
   ports:
     - "80:8080"
     - "443:8084"
   volumes:
     - "/etc/letsencrypt/live/${HOSTNAME}:/etc/ssl"
      - "tomcat/server.xml:/usr/local/tomcat/conf/server.xml"
